- hosts: all
  remote_user: "{{ rpi_user }}"
  become: yes
  vars:
    ansible_user: "{{ rpi_user }}"
    ansible_become_pass: "{{ rpi_plaintext_password }}"
    ansible_ssh_pass: "{{ rpi_plaintext_password }}"
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
    - name: Setup camera cronjob
      cron:
        name: Zanzocam
        job: "source /home/{{ rpi_user }}/webcam/venv/bin/activate; cd /home/{{ rpi_user }}/webcam && /home/{{ rpi_user }}/webcam/venv/bin/python3 /home/{{ rpi_user }}/webcam/camera.py >> /home/{{ rpi_user }}/webcam/logs.txt 2&>1"
        minute: "*/5"
        cron_file: zanzocam
        user: "{{ rpi_user }}"
        state: present
    
    - name: Disable the micro-HDMI port to save power
      blockinfile: 
        dest: "/etc/rc.local"
        insertbefore: "exit 0"  
        state: present
        block: "
        |
        |# Disable the HDMI port (to save power)
        |/usr/bin/tvservice -o
        |"
      
        
        
    
