- hosts: raspberry
  remote_user: "pi"
  become: yes
  vars:
    server_url: "{{ url }}"
    server_username: "{{ server_username }}"
    server_password: "{{ server_password }}"
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
    - name: Install graphic libs
      apt:
        name: 
          - libopenjp2-7-dev 
          - libtiff-dev
        state: present
       
    - name: Install DejaVu font
      apt:
        name: fonts-dejavu
        state: present
    
    - name: Install Python3
      apt:
        name: python3
        state: present
    
    - name: Install pip3
      apt:
        name: python3-pip
        state: present
        
    - name: Install venv module
      apt:
        name: python3-venv
        state: present
    
    - name: Copy Zanzocam Python files in /home/pi/webcam
      copy:
        src: ../webcam/
        dest: /home/pi/webcam
        
    - name: Setup virtualenv
      pip:
        requirements: /home/pi/webcam/requirements.txt
        virtualenv: /home/pi/webcam/venv
        virtualenv_command: '/usr/bin/python3 -m venv'
            
    - name: Add server address to the configuration.json file
      replace:
        path: /home/pi/webcam/configurazione.json
        regexp: "SERVER_ADDRESS"
        replace: "{{ server_url }}"

    - name: Append credentials to .bashrc
      blockinfile:
        path: /home/pi/.bashrc
        marker: "# Zanzocam settings"
        state: present
        block: |
            export RPICAM_SERVER_USERNAME={{ server_username }}"
            export RPICAM_SERVER_PWD={{ server_password }}"
        
    - name: Setup camera cronjob
      cron:
        name: Zanzocam
        job: "cd /home/pi/webcam && /home/pi/webcam/venv/bin/python3 /home/pi/webcam/camera.py > /home/pi/webcam/logs.txt 2>&1"
        minute: "*/5"
        cron_file: zanzocam
        user: pi
        state: present
        
    - name: Give Pi ownership over the files in webcam
      file:
        path: /home/pi/webcam
        owner: pi
        group: pi
        state: directory
        recurse: yes
        
    
