name: Unit Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install ZanzoCam
        run: |
          sudo apt-get install language-pack-it wireless-tools
          pip install Pillow requests piexif pytest pytest-coverage pytest-subprocess freezegun coveralls
          pip install --no-deps -e .

      - name: Unit tests
        run: coverage run --source=zanzocam/webcam -m pytest tests/unit_tests/

      - name: Coveralls.io
        run: coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
          COVERALLS_PARALLEL: true
          COVERALLS_SERVICE_NAME: 'github'
