name: Docs
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
 
  build_docs:
    runs-on: ubuntu-latest
 
    steps:
    - name: Prerequisites
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        apt-get update
        apt-get install -y git
        git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        
        apt-get install language-pack-it wireless-tools
        pip install Pillow requests piexif sphinx sphinx-rtd-theme
        pip install --no-deps -e .
      shell: bash
 
    - name: Build the docs and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "docs/build_docs.sh"
      shell: bash
